all:
	# For testing, form is blackWhite AI
	g++ main.cpp -o main
	g++ server.cpp -o server -lsocket -lresolv
	g++ easyEasy.cpp -o easyEasyTest
	g++ easyMedium.cpp -o easyMedTest
	g++ easyHard.cpp -o easyHardTest
	g++ mediumEasy.cpp -o medEasyTest
	g++ mediumMedium.cpp -o medMedTest
	g++ mediumHard.cpp -o medHardTest
	g++ hardEasy.cpp -o hardEasyTest
	g++ hardMedium.cpp -o hardMedTest
	g++ hardHard.cpp -o hardHardTest